config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'
  post 'tasks', to: 'tasks#create'
  delete 'tasks/:id', to: 'tasks#destroy'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task, local: true, html: { class: 'container' } do |form| %>
  <div class="form-group">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :details, class: 'form-label' %>
    <%= form.text_area :details, class: 'form-control' %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :completed, class: 'form-check-input' %>
    <%= form.label :completed, class: 'form-check-label' %>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class="my-4">My tasks</h1>
  <div class="list-group">
    <% @tasks.each do |task| %>
  <div class="list-group-item">
    <div class="d-flex justify-content-between">
      <h5 class="mb-1">
        <% if task.completed %>
          <i class="fas fa-check-square"></i>
        <% else %>
          <i class="far fa-square"></i>
        <% end %>
        <%= link_to task.title, task_path(task) %>
      </h5>
      <div>
        <%= link_to 'Edit', edit_task_path(task), class: 'btn btn-primary btn-sm mr-2' %>
        <%= link_to 'Delete', task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger btn-sm' %>
      </div>
    </div>
  </div>
<% end %>
  </div>
  <%= link_to "Create task", new_task_path, class: 'btn btn-success mt-3' %>
</div>

app/views/tasks/new.html.erb
<%= form_with model: @task, local: true, html: { class: 'container' } do |form| %>
  <div class="form-group">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :details, class: 'form-label' %>
    <%= form.text_area :details, class: 'form-control' %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :completed, class: 'form-check-input' %>
    <%= form.label :completed, class: 'form-check-label' %>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<div class="container">
  <h1 class="my-4"><%= @task.title %></h1>
  <p class="lead"><%= @task.details %></p>
  <%= link_to "Back to list", root_path, class: 'btn btn-secondary' %>
</div>